site_name: 巴斯的iOS安全学习记录
site_url: https://ios.macoder.tech
site_author: 巴斯.zznQ
site_description: "巴斯的iOS安全学习记录"
repo_name: ac0d3r/ios
repo_url: https://github.com/ac0d3r/ios
copyright: Copyright &copy; 2022 巴斯.zznQ
extra:
  generator: false
  social:
    - icon: fontawesome/brands/redhat
      link: https://blog.macoder.tech
      name: 巴斯.zznQ
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ac0d3r
      name: 巴斯光年's twitter
    - icon: fontawesome/brands/github
      link: https://github.com/ac0d3r
      name: 巴斯光年's github

theme:
  name: material
  custom_dir: overrides
  language: zh
  font: false
  icon:
    logo: material/apple
  features:
    - navigation.tabs
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tracking
    - navigation.expand
    - navigation.top
  favicon: assets/images/favicon.png
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: 切换深色模式
    - scheme: slate
      toggle:
        icon: material/brightness-5
        name: 切换浅色模式
plugins:
  - git-revision-date
  - search

# Page tree
nav:
  - 主页: index.md
  - 越狱: 1-越狱/1.md
  - 工具准备:
      - macOS上的工具: 2-工具准备/1.md
      - iOS上的工具: 2-工具准备/2.md
  - 砸壳: 3-砸壳/1.md
